Use list(sequence) to fix test failure
Fixes error in map array result comparison because of difference in return
values and bool list behavior on python3:
"""
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
"""